development:
  sessions:
    default:
      database: beat-development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: beat-test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: beat-production
      hosts:
        - localhost:27017
